# Generated by Django 6.0.4 on 2026-06-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='urgencia',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('AF', 'A Fazer'), ('EA', 'Em Andamento'), ('CO', 'Concluído')], default='AF', max_length=2),
        ),
    ]
